# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: discord-one-way-calendar

on:
  workflow_dispatch:
  repository_dispatch:
  push:
    branches: 
    - main
  schedule:
    - cron: "0 16 * * *"


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Set up Python
      uses: actions/setup-python@main
      with:
        python-version: 3.11
    - name: "Set up requests"
      run: |
       pip install requests
    - name: "run main.py"
      env:
        bot_token: ${{secrets.bot_token}}
      run: |
        python main.py
    - name: Delete old workflow run using Personal Token
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ secrets.PAT }}
        repository: ${{ github.repository }}
        retain_days: 0
        keep_minimum_runs: 0
        delete_workflow_pattern: "discord-one-way-calendar"
